# Generated by Django 2.1.7 on 2021-05-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_auto_20190422_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email_from',
            field=models.CharField(default='any_email@domain.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='staffnewsletter',
            name='email_from',
            field=models.CharField(default='any_email@domain.com', max_length=200),
        ),
    ]
